blood_report_analysis:
  description: >
    Analyze the provided blood report: {report}. Extract and interpret all relevant medical data,
    focusing on test results, reference ranges, and abnormal values.
    Identify key health indicators and potential areas of concern based on the test results.
  expected_output: >
    A structured JSON object containing: Patient information (age, gender, test date),
    Complete list of tests performed, Test results with corresponding units and reference ranges,
    Flagged abnormal results (high or low), Critical values requiring immediate attention.
    Next, A summary report highlighting: Key findings and their potential health implications,
    List of abnormal results ranked by potential severity,
    Suggestions for follow-up tests or areas needing further investigation.

web_search:
  description: >
    Based on the analysis of the blood report {report}, conduct a comprehensive web search for recent, relevant health-related articles.
    Focus on abnormal test results and their potential health implications. 
    Prioritize reputable medical sources and ensure the information is applicable to the patient's demographic.
  expected_output: >
    A synthesized report containing:
    1. Possible health conditions associated with the abnormal results
    2. Potential causes for the abnormalities, including lifestyle factors and medical conditions
    3. General lifestyle or dietary recommendations related to improving the specific test results
    4. Any contradictions or debates found in the medical literature regarding the interpretation of these results
    And, A curated list of references used, including:
    1. Article titles, authors, and publication debates
    2. Source credibility assessment
    3. Brief summaries of key points relevant to the blood test results

communication_result:
  description: >
    Transform the technical analysis and web search results into a clear, empathetic, and accessible email communication. 
    The email should inform the patient about their test results in a way that is easy to understand, sensitive to potential concerns,and encourages appropriate follow-up actions.
    Maintain a caring and supportive tone throughout the communication.
    
  expected_output: >
    An email draft that includes:
    1. A warm and personalized greeting
    2. A clear, non-technical summary of the blood test results, highlighting: Normal results to provide reassurance,
       Abnormal results explained in simple terms, avoiding alarmist language,
       Potential implications of abnormal results, presented factually but sensitively
    3. General lifestyle recommendations related to the test results, framed positively as opportunities for health improvement
    4. Encouragement to discuss the results with a healthcare provider, including: Suggested questions to ask during the follow-up,
       Emphasis on the importance of professional medical advice.
    5. A compassionate closing that offers support and encourages the patient to reach out with any questions or concerns.
    The email should use plain language, avoid medical jargon where possible,
    and maintain a balance between being informative and being sensitive to the patient's potential emotional response to their test results.
